### ISSUE TITLE
Make it work

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-python-migration-tools#1]
## Current output

For typhos, this tool outputs:
```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools", "versioneer[toml]",]

[project]
classifiers = [ "Programming Language :: Python :: 3",]
description = "Interface generation for ophyd devices"
dynamic = [ "version", "readme", "dependencies", "optional-dependencies",]
keywords = []
name = "typhos"
requires-python = ">=3.9"
[[project.authors]]
name = "SLAC National Accelerator Laboratory"

[project.license]
file = "LICENSE.md"

[project.scripts]
typhos = "typhos.cli:main"

[tool.versioneer]
vcs = "git"
style = "pep440"
versionfile_source = "typhos/_version.py"
versionfile_build = "typhos/_version.py"
tag_prefix = "v"

[project.entry-points."pydm.widget"]
TyphosAlarmCirclePlugin = "typhos.alarm:TyphosAlarmCircle"
TyphosAlarmEllipsePlugin = "typhos.alarm:TyphosAlarmEllipse"
TyphosAlarmPolygonPlugin = "typhos.alarm:TyphosAlarmPolygon"
TyphosAlarmRectanglePlugin = "typhos.alarm:TyphosAlarmRectangle"
TyphosAlarmTrianglePlugin = "typhos.alarm:TyphosAlarmTriangle"
TyphosCompositeSignalPanelPlugin = "typhos.panel:TyphosCompositeSignalPanel"
TyphosDeviceDisplayPlugin = "typhos.display:TyphosDeviceDisplay"
TyphosDisplaySwitcherPlugin = "typhos.display:TyphosDisplaySwitcher"
TyphosDisplayTitlePlugin = "typhos.display:TyphosDisplayTitle"
TyphosHelpFramePlugin = "typhos.display:TyphosHelpFrame"
TyphosMethodButtonPlugin = "typhos.func:TyphosMethodButton"
TyphosPositionerWidgetPlugin = "typhos.positioner:TyphosPositionerWidget"
TyphosRelatedSuiteButtonPlugin = "typhos.related_display:TyphosRelatedSuiteButton"
TyphosSignalPanelPlugin = "typhos.panel:TyphosSignalPanel"

[project.entry-points."pydm.data_plugin"]
HappiPlugin = "typhos.plugins:HappiPlugin"
SignalPlugin = "typhos.plugins:SignalPlugin"

[tool.setuptools.packages.find]
where = [ "typhos",]
include = []
namespaces = false

[tool.setuptools.dynamic.readme]
file = "README.md"

[tool.setuptools.dynamic.dependencies]
file = [ "requirements.txt",]

[tool.setuptools.dynamic.optional-dependencies.test]
file = "dev-requirements.txt"
```

## Status

* It installs 🥳 ... but doesn't import 😦 

## Issues to fix
- [ ] Make the import actually work (presumably due to `find_packages` replacement 'tool.setuptools.packages.find' not working properly)
- [ ] Fix versioneer: `Successfully installed typhos-0.0.0`
- [ ] Verify that entrypoints actually work
- [ ] Verify that the other metadata is correct
